version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    # command: tail -f /dev/null
    command: uvicorn main:app --reload --port=8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    command: npm run dev
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongoData:/mongoData/db
  reverse_proxy:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
