version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    # command: tail -f /dev/null
    command: uvicorn main:app --reload --port=8000
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./frontend:/app
    command: npm run dev
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongoData:/mongoData/db
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
# Mongo express but configured for localhost
  mongo-express:
    image: mongo-express
    network_mode: host
    environment:
      ME_CONFIG_MONGODB_SERVER: localhost
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    restart: unless-stopped

