version: '3.3'

services:
# -------------------- Backend --------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    # command: tail -f /dev/null
    command: uvicorn main:app --reload --port=8000
    volumes:
      - ./backend:/app
# -------------------- Frontend --------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./frontend:/frontend
    command: npm run dev
# -------------------- Nginx --------------------
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
# -------------------- MongoDB --------------------
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/mongoData:/data/db
# -------------------- Mongo-Express --------------------
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
